Change CRYPTOPP_SOURCES to a path variable
abdes/cryptopp-cmake pull request #19
Opened 2022-08-31 11:29 UTC by chausner

This changes `CRYPTOPP_SOURCES` from an option (which are intended only for [boolean values](https://cmake.org/cmake/help/latest/command/option.html)) to a path cache variable. The latter correctly translates backward-slash path separators on Windows to forward slashes. Previously, attempting to set this variable to a Windows-style path would result in errors like this:
```
CMake Error at cryptopp/CMakeLists.txt:1078 (add_library):
  Syntax error in cmake code when parsing string

    C:\Users\Admin\.conan\data\cryptopp\8.7.0\_\_\build\5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b\src/zlib.cpp

  Invalid character escape '\U'.
```

2022-09-01 11:23 UTC, abdes commented
Makes a lot of sense @chausner .
However, would you please do the same than what @Vollstrecker did and allow to use any pre-existing normal cmake variable with the same name? (see his change for the include prefix).

2022-09-01 11:24 UTC, abdes requested changes
Test for existing cmake normal variable with same name and use its value.

2022-09-01 16:39 UTC, chausner commented
> However, would you please do the same than what @Vollstrecker did and allow to use any pre-existing normal cmake variable with the same name? (see his change for the include prefix).

Okay, done in f335c2d2064c19013989d104c84544ad8b5380c7.

2022-09-02 06:42 UTC, abdes approved these changes

2022-09-02 06:47 UTC, abdes commented
For history and future references to this change, https://cmake.org/cmake/help/latest/policy/CMP0126.html#policy:CMP0126, only available from CMake version 3.21. One day, we need to go back to these changes and align with CMP0126.

2022-09-02 07:16 UTC, Vollstrecker commented
> For history and future references to this change, https://cmake.org/cmake/help/latest/policy/CMP0126.html#policy:CMP0126, only available from CMake version 3.21. One day, we need to go back to these changes and align with CMP0126.

Not really, as -D from cmdline also sets cache variables and 126 affects only normal vs. cache entries. What we should do is using FORCE to update the type and helpstring (iirc),

2022-09-02 18:50 UTC, merged