chore: moved project upwards
abdes/cryptopp-cmake pull request #80
Opened 2023-04-21 14:35 UTC by Vollstrecker

It was less to change than I thought, After seeing that the revision isn't used the gitrevision files have been dropped also, if we really need something from there, the git executable can be used directly to get this.

If the versionupdate script is really needed, someone has to adapt it to being able to use with the new versioning, or we drop it also, as changing some numbers isn't that hard. Also we could get this directly from git.

2023-04-21 19:51 UTC, abdes commented
The versionupdate is really needed. It integrates with `standard-version` for automatic release process. If it's broken, then the release process will become manual again.

Is it really necessary to delete all the META variables?

2023-04-21 20:50 UTC, Vollstrecker commented
It's not needed to delete them, it's just setting var to feed a command that creates vars with the same value ... I won't say it's the dumbest concept I've heard of, but it's in the top ten. Bonuspoints for being part of a concept that is really useful.

2023-04-22 05:26 UTC, abdes commented
It's typical of CMake. The reason why such variables were used is their name. It does not have the project name in them. That allows me to reuse code in cmake common modules and reuse tools across projects. CMake variables are project specific.

Sometimes the concept looks dumb but some things deep below justify it 😁

2023-04-22 06:00 UTC, Vollstrecker commented
> CMake variables are project specific.

Which is really helpful in chainbuild setups.

> In some other projects, I use these variable to also customize doxygen and sphinx docs.

You use these tools outside the project to create docs for the project that read these information from the project? I didn't check for sphinx, but using doxygen is builtin, and I guess there's a reason.

> I think it's CMake trying to be too helpful when it should not or at least not like that grin.

It's not always perfect how to implement something, but they provide everything to enable customization to make it fit into the whole thing like you need it.

> Sometimes the concept looks dumb but some things deep below justify it

I'll let you know when I find. Anyway, the vars back.

2023-04-22 07:41 UTC, abdes requested changes
You removed CRYPTOPP_VERSION but forgot to update the config.pc.in which uses it.

2023-04-23 07:50 UTC, abdes approved these changes

2023-04-23 07:52 UTC, merged